version: "3.8"

services:
  db:
    image: postgres:17
    container_name: tcss460-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: christian
      POSTGRES_PASSWORD: 62097600
      POSTGRES_DB: group_project_backend_3
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: