openapi: 3.0.3
info:
  title: TCSS 460 Group Project API
  description: |
    **Team:** [Group 3]
    **Deployed URL:** [https://group-project-backend-group-3-1.onrender.com]

    A RESTful API for the TCSS 460 group project.
  version: 0.1.0

servers:
  - url: http://localhost:3000
    description: Local development
  - url: https://group-project-backend-group-3-1.onrender.com
    description: Deployed server on Render

tags:
  - name: Heartbeat
    description: HTTP request to verify server is alive

paths:
  /heartbeat:
    get:
      tags: [Heartbeat]
      summary: GET heartbeat status
      description: Returns a message declaring that the server is alive
      responses:
        '200':
          description: A confirmation message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeartbeatResponse'

components:
  schemas:
    HeartbeatResponse:
      type: object
      properties:
        message:
          type: string
          example: 'The server is alive!'
